#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-2.1-or-later
"""Regenerate app/src/main/cpp/glyph_table.inc from xrenv/spec.py.

The `text` primitive of ARCHITECTURE.md §2 is tessellated from a built-in
stroke font. The font lives in the Python reference tessellator
(``xrenv.spec._GLYPHS``) and the C++ renderer must mirror it exactly, so the
table is generated rather than transcribed:

    python3 quest/tools/gen_glyphs.py            # writes glyph_table.inc
    python3 quest/tools/gen_glyphs.py --check    # fails if it is out of date

Every coordinate in the Python table is a multiple of 0.01 in the 0..1 glyph
box, so they are stored as signed hundredths and divided by 100 at load time,
which reproduces the Python doubles bit for bit.
"""

from __future__ import annotations

import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
QUEST = os.path.dirname(HERE)
MOD_XR = os.path.dirname(QUEST)
OUTPUT = os.path.join(QUEST, "app", "src", "main", "cpp", "glyph_table.inc")


def build() -> str:
    sys.path.insert(0, MOD_XR)
    from xrenv import spec  # noqa: E402  (path set up above)

    glyphs = spec._GLYPHS
    lines = [
        "// Generated by quest/tools/gen_glyphs.py from xrenv/spec.py (_GLYPHS).",
        "// Do not edit by hand: run the generator so the headset and the desktop",
        "// draw the same letters.",
        "//",
        "// Encoding, per glyph: the number of polylines, then for each polyline the",
        "// point count followed by x,y pairs in hundredths of the cap height.",
        "",
    ]
    entries = []
    for ch in sorted(glyphs, key=ord):
        polys = glyphs[ch]
        cp = ord(ch)
        parts = []
        for poly in polys:
            coords = []
            for x, y in poly:
                for v in (x, y):
                    scaled = round(v * 100.0)
                    if abs(v * 100.0 - scaled) > 1e-9:
                        raise SystemExit(
                            "glyph %r coordinate %r is not a multiple of 0.01" % (ch, v)
                        )
                    if not -128 <= scaled <= 127:
                        raise SystemExit("glyph %r coordinate %r out of int8 range" % (ch, v))
                    coords.append(str(scaled))
            parts.append("%d, %s" % (len(poly), ", ".join(coords)))
        body = "%d" % len(polys)
        if parts:
            body += ", " + ", ".join(parts)
        lines.append("static const signed char kGlyph_%04X[] = {%s};" % (cp, body))
        entries.append((cp, ch))

    lines.append("")
    lines.append("static const GlyphEntry kGlyphTable[] = {")
    for cp, ch in entries:
        label = ch if ch.isprintable() and ch not in "\\" else repr(ch)
        lines.append("    {0x%04Xu, kGlyph_%04X},  // %s" % (cp, cp, label))
    lines.append("};")
    lines.append("")
    lines.append("// Layout constants, mirrored from xrenv/spec.py.")
    lines.append("static const float kGlyphAdvance = %.10gf;  // _TEXT_ADVANCE" % spec._TEXT_ADVANCE)
    lines.append("static const float kGlyphWidth = %.10gf;    // _GLYPH_W" % spec._GLYPH_W)
    lines.append("static const float kGlyphStroke = %.10gf;   // _TEXT_STROKE" % spec._TEXT_STROKE)
    lines.append("static const float kGlyphLinePitch = 1.4f;  // _tess_text line_pitch")
    lines.append("")
    return "\n".join(lines)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="only verify that the file is current")
    ap.add_argument("-o", "--output", default=OUTPUT)
    args = ap.parse_args(argv)

    text = build()
    if args.check:
        try:
            with open(args.output, "r", encoding="utf-8") as fh:
                current = fh.read()
        except OSError:
            current = None
        if current != text:
            sys.stderr.write("%s is out of date; run gen_glyphs.py\n" % args.output)
            return 1
        print("%s is up to date" % args.output)
        return 0

    with open(args.output, "w", encoding="utf-8") as fh:
        fh.write(text)
    print("wrote %s (%d glyphs)" % (args.output, text.count("static const signed char")))
    return 0


if __name__ == "__main__":
    sys.exit(main())
