# SPDX-License-Identifier: LGPL-2.1-or-later
"""Toolpath parsing, playback and the machine checks."""

import math
import os
import sys
import unittest

MODULE_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if MODULE_ROOT not in sys.path:
    sys.path.insert(0, MODULE_ROOT)

from xrcam import (CamSession, MachineSpec, Player, check_bounds, check_collisions, format_time,  # noqa: E402
                   from_path_commands, parse_gcode, world_polyline)
from xrfit import box_mesh  # noqa: E402
from xrsketch import vecmath as vm  # noqa: E402

PRINT = """; generated by test slicer
M104 S210
G21
G90
M82
G92 E0
;LAYER:0
;Z:0.2
G0 F6000 X10 Y10 Z0.2
G1 F1200 X60 Y10 E2.5
G1 X60 Y60 E5.0
G1 X10 Y60 E7.5
G1 X10 Y10 E10.0
;LAYER:1
;Z:0.4
G0 Z0.4
G1 X60 Y10 E12.5 F1800
G2 X70 Y20 I10 J0 E13.0
"""

MILL = """(Operation: Profile)
G21 G90
G0 Z15
G0 X0 Y0
M3 S12000
G1 Z-2 F300
G1 X50 F600
G3 X60 Y10 I0 J10
G1 Y40
G0 Z15
M5
"""


class GcodeTest(unittest.TestCase):
    def test_printer_file(self):
        tp = parse_gcode(PRINT, name="cube")
        self.assertEqual(tp.machine, "printer")
        self.assertEqual(tp.layers, [0, 1])
        cutting = [s for s in tp.segments if s.cutting]
        self.assertEqual(len(cutting), 6)
        self.assertAlmostEqual(cutting[0].feed, 20.0)  # 1200 mm/min
        self.assertAlmostEqual(cutting[0].length, 50.0)
        self.assertAlmostEqual(cutting[0].duration, 2.5)
        self.assertAlmostEqual(cutting[0].extrusion, 2.5)
        arc = tp.segments[-1]
        self.assertIsNotNone(arc.arc)
        self.assertAlmostEqual(arc.length, math.pi * 10 / 2.0, places=6)
        self.assertEqual(arc.layer, 1)
        self.assertEqual(arc.z_layer, 0.4)
        first_rapid = tp.segments[0]
        self.assertTrue(first_rapid.rapid)
        self.assertAlmostEqual(first_rapid.feed, 100.0)
        self.assertGreater(tp.duration, 0)
        self.assertEqual(tp.bounds(cutting_only=True)[0], (10.0, 10.0, 0.2))

    def test_mill_file(self):
        tp = parse_gcode(MILL, name="profile")
        self.assertEqual(tp.machine, "mill")
        cuts = [s for s in tp.segments if s.cutting]
        self.assertEqual(len(cuts), 4)
        self.assertEqual(cuts[0].operation, "Profile")
        self.assertEqual(cuts[0].power, 12000.0)
        arc = cuts[2]
        self.assertFalse(arc.arc[1], "G3 is counter-clockwise")
        self.assertAlmostEqual(arc.length, math.pi * 10 / 2.0, places=6)
        pts = arc.polyline(0.01)
        self.assertGreater(len(pts), 10)
        self.assertAlmostEqual(math.dist(pts[len(pts) // 2][:2], (50, 10)), 10.0, places=3)
        self.assertFalse(tp.segments[-1].cutting, "after M5")

    def test_relative_inches_and_radius_arcs(self):
        text = "G20\nG91\nG1 X1 F60\nG2 X1 Y1 R1\nG90 G21\nG92 X0 Y0\nG1 X5\n"
        tp = parse_gcode(text)
        self.assertAlmostEqual(tp.segments[0].length, 25.4)
        self.assertAlmostEqual(tp.segments[1].length, math.pi * 25.4 / 2.0, places=4)
        self.assertEqual(tp.segments[2].end, (5.0, 0.0, 0.0))
        self.assertEqual(parse_gcode("; nothing\nM117 hi\n").notes, ["no motion commands found"])

    def test_layer_change_comments(self):
        tp = parse_gcode(";LAYER_CHANGE\nG1 X1 F100\n;LAYER_CHANGE\nG1 X2\n")
        self.assertEqual(tp.layers, [1, 2])

    def test_from_path_commands(self):
        cmds = [{"Name": "G0", "Parameters": {"X": 0, "Y": 0, "Z": 10}},
                {"Name": "G1", "Parameters": {"Z": -1, "F": 300}},
                {"Name": "G1", "Parameters": {"X": 20}},
                {"Name": "G2", "Parameters": {"X": 30, "Y": 10, "I": 0, "J": 10}},
                {"Name": "G0", "Parameters": {"Z": 10}}]
        tp = from_path_commands(cmds, "Pocket", clearance_z=5.0)
        self.assertEqual([s.cutting for s in tp.segments], [False, True, True, True, False])
        self.assertTrue(tp.segments[3].arc[1])
        self.assertEqual(tp.segments[1].operation, "Pocket")


class PlayerTest(unittest.TestCase):
    def test_transport(self):
        tp = parse_gcode(PRINT)
        p = Player(tp)
        self.assertFalse(p.advance(1.0))
        p.play()
        p.advance(0.5)
        self.assertGreater(p.time, 0)
        p.set_speed(10.0)
        p.advance(0.1)
        self.assertAlmostEqual(p.time, 1.5)
        p.seek_fraction(1.0)
        self.assertAlmostEqual(p.progress, 1.0)
        self.assertTrue(p.advance(0.1) is False)
        self.assertFalse(p.playing)
        p.stop()
        self.assertEqual(p.time, 0.0)
        p.loop = True
        p.play()
        p.advance(p.duration / 10.0 + 0.01)
        self.assertTrue(p.playing)
        self.assertLess(p.time, p.duration)

    def test_position_and_layers(self):
        tp = parse_gcode(PRINT)
        p = Player(tp)
        p.seek(tp.segments[0].duration + 1.25)  # halfway along the first 50 mm extrusion (2.5 s)
        self.assertEqual(p.index, 1)
        self.assertAlmostEqual(p.fraction_in_segment, 0.5)
        self.assertAlmostEqual(p.position[0], 35.0)
        self.assertTrue(p.cutting)
        p.goto_layer(1)
        self.assertEqual(p.layer, 1)
        done, current = p.completed()
        self.assertEqual(len(done), 5)
        self.assertEqual(current[1], 0.0)
        p.goto_layer(99)
        self.assertEqual(p.layer, 1, "nearest layer")
        self.assertEqual(format_time(3725), "1:02:05")
        self.assertEqual(format_time(65), "1:05")
        self.assertIn("remaining", CamSession(tp, MachineSpec()).status())

    def test_empty(self):
        p = Player(parse_gcode(""))
        self.assertEqual(p.index, -1)
        self.assertEqual(p.position, (0.0, 0.0, 0.0))
        self.assertEqual(p.progress, 1.0)


class MachineTest(unittest.TestCase):
    def spec(self):
        return MachineSpec("test", bed=(200.0, 200.0), height=200.0, anchor_position=(1.0, 0.5, -0.2))

    def test_mapping_round_trip(self):
        m = self.spec()
        w = m.to_world((0.0, 0.0, 0.0))
        self.assertEqual([round(c, 6) for c in w], [0.9, 0.4, -0.2], "corner origin maps to the plate's corner")
        centre = m.to_world((100.0, 100.0, 50.0))
        self.assertEqual([round(c, 6) for c in centre], [1.0, 0.5, -0.15])
        back = m.from_world(centre)
        self.assertEqual([round(c, 6) for c in back], [100.0, 100.0, 50.0])
        m.origin = "center"
        self.assertEqual([round(c, 6) for c in m.to_world((0, 0, 0))], [1.0, 0.5, -0.2])

    def test_rotated_anchor(self):
        from xrassembly.mates import rotation_about

        # The environment's plate is +Z-normal in anchor frame; rotate it to lie flat in a Y-up world.
        q = rotation_about((1, 0, 0), -math.pi / 2)
        m = MachineSpec("p", bed=(100, 100), anchor_position=(0, 1, 0), anchor_rotation=q)
        w = m.to_world((50.0, 50.0, 10.0))
        self.assertAlmostEqual(w[1], 1.01, msg="+Z of the machine becomes +Y (up)")
        self.assertEqual([round(c, 6) for c in m.from_world(w)], [50.0, 50.0, 10.0])

    def test_from_environment_spec(self):
        spec = {"id": "bambu_x1c", "name": "X1C", "bounds": [0.6, 0.6, 0.6],
                "anchors": {"build_plate": {"position": [0, 0.1, 0], "rotation": [0, 0, 0, 1], "size": [0.256, 0.256]}}}
        m = MachineSpec.from_environment_spec(spec)
        self.assertEqual(m.bed, (256.0, 256.0))
        self.assertEqual(m.kind, "printer")
        self.assertAlmostEqual(m.height, 360.0)
        with self.assertRaises(ValueError):
            MachineSpec.from_environment_spec({"id": "void"})
        laser = MachineSpec.from_environment_spec({"id": "laser_cutter", "anchors": {"bed": {"position": [0, 0, 0], "size": [1.3, 0.9]}}})
        self.assertEqual(laser.kind, "laser")

    def test_bounds_check(self):
        m = self.spec()
        tp = parse_gcode("G1 X10 Y10 F600\nG1 X250 Y10\nG1 X10 Y-5\nG1 Z300\n")
        issues = check_bounds(tp, m)
        self.assertEqual([i.segment for i in issues], [1, 2, 3])
        self.assertEqual(issues[0].kind, "out_of_bounds")
        self.assertIn("250.0", issues[0].message)
        self.assertGreater(issues[1].time, issues[0].time)

    def test_collision_check(self):
        m = MachineSpec("test", bed=(200.0, 200.0), head_radius=10.0, head_height=30.0)
        # a 20 mm tall clip at x=100, right on the path at z=1
        clip = box_mesh((10, 10, 20), center=(100.0, 50.0, 10.0))
        tp = parse_gcode("G1 X0 Y50 Z1 F600\nG1 X200 Y50\nG0 Z50\nG1 X0 Y50\n")
        issues = check_collisions(tp, m, {"clip": (clip, None)}, step=2.0)
        self.assertEqual(len(issues), 1)
        self.assertEqual(issues[0].obstacle, "clip")
        self.assertEqual(issues[0].segment, 1)
        self.assertGreater(issues[0].time, 0.0)
        # raising the path clears it
        high = parse_gcode("G1 X0 Y50 Z40 F600\nG1 X200 Y50\n")
        self.assertEqual(check_collisions(high, m, {"clip": (clip, None)}), [])

    def test_world_polyline_and_session(self):
        m = self.spec()
        tp = parse_gcode(PRINT)
        lines = world_polyline(tp, m, cutting_only=True)
        self.assertEqual(len(lines), 6)
        self.assertTrue(all(cut for _, cut, _ in lines))
        s = CamSession(tp, m, {"clip": (box_mesh((5, 5, 5), center=(35.0, 10.0, 2.5)), None)})
        issues = s.check(step=1.0)
        self.assertTrue(any(i.kind == "collision" for i in issues))
        s.play()
        s.set_speed(1000.0)
        s.update(1.0)
        kinds = [e.kind for e in s.drain_events()]
        self.assertIn("collision", kinds)
        self.assertEqual(len(s.tool_position_world()), 3)


if __name__ == "__main__":
    unittest.main()
