# SPDX-License-Identifier: LGPL-2.1-or-later
# ***************************************************************************
# *   Copyright (c) 2026 FreeCAD XR workbench contributors                   *
# *                                                                         *
# *   This file is part of FreeCAD.                                         *
# *                                                                         *
# *   FreeCAD is free software: you can redistribute it and/or modify it    *
# *   under the terms of the GNU Lesser General Public License as           *
# *   published by the Free Software Foundation, either version 2.1 of the  *
# *   License, or (at your option) any later version.                       *
# ***************************************************************************
"""Shared 3D vector / quaternion / similarity-transform maths for ``xrsketch``.

Everything here is plain standard library: tuples in, tuples out, no numpy and
no Coin (ARCHITECTURE.md §6).  numpy is never imported anywhere in
``xrsketch``, so the "with numpy" and "without numpy" code paths are the same
code and cannot drift.

Quaternions are ``(x, y, z, w)``, the convention already used by
:mod:`xrenv.scale`; the four primitive quaternion operations are imported from
there rather than written a second time.

:class:`Transform` is a *similarity* transform — uniform scale, rotation,
translation — which is exactly the group generated by two-handed manipulation
(:mod:`xrsketch.bimanual`) and is closed under composition and inversion.
"""

import math

from xrenv.scale import (quat_conjugate, quat_from_axis_angle, quat_mul,
                         quat_rotate)

__all__ = [
    "EPS",
    "IDENTITY_QUAT",
    "Transform",
    "add",
    "angle_between",
    "any_perp",
    "clamp",
    "cross",
    "dist",
    "dot",
    "length",
    "lerp",
    "mat3_from_columns",
    "mat3_mul",
    "mat3_transpose",
    "mul",
    "neg",
    "normalize",
    "orthonormal_basis",
    "plane_from_points",
    "quat_conjugate",
    "quat_from_axis_angle",
    "quat_from_mat3",
    "quat_mul",
    "quat_normalize",
    "quat_rotate",
    "quat_to_axis_angle",
    "quat_to_mat3",
    "quat_slerp",
    "reflect_point",
    "reflect_vector",
    "sub",
    "vec3",
]

EPS = 1e-12
IDENTITY_QUAT = (0.0, 0.0, 0.0, 1.0)


# --------------------------------------------------------------------------
# vectors
# --------------------------------------------------------------------------

def vec3(p):
    """Coerce anything indexable to a ``(x, y, z)`` float tuple."""
    return (float(p[0]), float(p[1]), float(p[2]))


def add(a, b):
    return (a[0] + b[0], a[1] + b[1], a[2] + b[2])


def sub(a, b):
    return (a[0] - b[0], a[1] - b[1], a[2] - b[2])


def mul(a, s):
    return (a[0] * s, a[1] * s, a[2] * s)


def neg(a):
    return (-a[0], -a[1], -a[2])


def dot(a, b):
    return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]


def cross(a, b):
    return (a[1] * b[2] - a[2] * b[1],
            a[2] * b[0] - a[0] * b[2],
            a[0] * b[1] - a[1] * b[0])


def length(a):
    return math.sqrt(a[0] * a[0] + a[1] * a[1] + a[2] * a[2])


def dist(a, b):
    return length(sub(a, b))


def normalize(a, fallback=(0.0, 0.0, 0.0)):
    n = length(a)
    if n < EPS:
        return fallback
    return (a[0] / n, a[1] / n, a[2] / n)


def lerp(a, b, t):
    return (a[0] + (b[0] - a[0]) * t,
            a[1] + (b[1] - a[1]) * t,
            a[2] + (b[2] - a[2]) * t)


def clamp(v, lo, hi):
    return lo if v < lo else (hi if v > hi else v)


def any_perp(t):
    """Some unit vector perpendicular to ``t``."""
    ax, ay, az = abs(t[0]), abs(t[1]), abs(t[2])
    if ax <= ay and ax <= az:
        other = (1.0, 0.0, 0.0)
    elif ay <= az:
        other = (0.0, 1.0, 0.0)
    else:
        other = (0.0, 0.0, 1.0)
    v = cross(t, other)
    if length(v) < EPS:
        return (1.0, 0.0, 0.0)
    return normalize(v)


def angle_between(a, b):
    """Unsigned angle in radians between two vectors (0 for degenerate)."""
    na = normalize(a)
    nb = normalize(b)
    if length(na) < 0.5 or length(nb) < 0.5:
        return 0.0
    return math.acos(clamp(dot(na, nb), -1.0, 1.0))


def orthonormal_basis(primary, secondary=None):
    """Right handed basis ``(u, v, w)`` with ``u`` along ``primary``.

    ``secondary`` biases the second axis; it is Gram-Schmidt orthogonalised
    against ``u`` and replaced by an arbitrary perpendicular when it is
    parallel to it or missing.
    """
    u = normalize(primary)
    if length(u) < 0.5:
        return ((1.0, 0.0, 0.0), (0.0, 1.0, 0.0), (0.0, 0.0, 1.0))
    v = None
    if secondary is not None:
        s = vec3(secondary)
        v = sub(s, mul(u, dot(s, u)))
        if length(v) < 1e-9:
            v = None
        else:
            v = normalize(v)
    if v is None:
        v = any_perp(u)
    w = cross(u, v)
    return (u, v, w)


def plane_from_points(points):
    """Best fit plane ``(origin, normal, max_deviation)`` of a point cloud.

    The normal is the eigenvector of the smallest eigenvalue of the covariance
    matrix, found with a cyclic Jacobi sweep (pure Python, no numpy).
    Fewer than three points gives ``None``.
    """
    pts = [vec3(p) for p in points]
    n = len(pts)
    if n < 3:
        return None
    cx = sum(p[0] for p in pts) / n
    cy = sum(p[1] for p in pts) / n
    cz = sum(p[2] for p in pts) / n
    origin = (cx, cy, cz)
    cov = [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]]
    for p in pts:
        d = (p[0] - cx, p[1] - cy, p[2] - cz)
        for i in range(3):
            for j in range(3):
                cov[i][j] += d[i] * d[j]
    vals, vecs = _jacobi_eigen(cov)
    k = min(range(3), key=lambda i: vals[i])
    normal = normalize((vecs[0][k], vecs[1][k], vecs[2][k]),
                       (0.0, 0.0, 1.0))
    dev = max(abs(dot(sub(p, origin), normal)) for p in pts)
    return (origin, normal, dev)


def _jacobi_eigen(a, sweeps=24):
    """Eigenvalues/vectors of a symmetric 3x3 matrix (columns are vectors)."""
    m = [row[:] for row in a]
    v = [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]
    for _ in range(sweeps):
        off = abs(m[0][1]) + abs(m[0][2]) + abs(m[1][2])
        if off < 1e-18:
            break
        for p, q in ((0, 1), (0, 2), (1, 2)):
            if abs(m[p][q]) < 1e-18:
                continue
            theta = (m[q][q] - m[p][p]) / (2.0 * m[p][q])
            t = (1.0 if theta >= 0.0 else -1.0) / \
                (abs(theta) + math.sqrt(theta * theta + 1.0))
            c = 1.0 / math.sqrt(t * t + 1.0)
            s = t * c
            for k in range(3):
                mkp = m[k][p]
                mkq = m[k][q]
                m[k][p] = c * mkp - s * mkq
                m[k][q] = s * mkp + c * mkq
            for k in range(3):
                mpk = m[p][k]
                mqk = m[q][k]
                m[p][k] = c * mpk - s * mqk
                m[q][k] = s * mpk + c * mqk
            for k in range(3):
                vkp = v[k][p]
                vkq = v[k][q]
                v[k][p] = c * vkp - s * vkq
                v[k][q] = s * vkp + c * vkq
    return ([m[0][0], m[1][1], m[2][2]], v)


def reflect_point(p, origin, normal):
    """Mirror a point across the plane ``(origin, normal)``."""
    n = normalize(normal)
    d = dot(sub(p, origin), n)
    return sub(p, mul(n, 2.0 * d))


def reflect_vector(v, normal):
    n = normalize(normal)
    return sub(v, mul(n, 2.0 * dot(v, n)))


# --------------------------------------------------------------------------
# quaternions and 3x3 matrices
# --------------------------------------------------------------------------

def quat_normalize(q):
    n = math.sqrt(q[0] * q[0] + q[1] * q[1] + q[2] * q[2] + q[3] * q[3])
    if n < EPS:
        return IDENTITY_QUAT
    return (q[0] / n, q[1] / n, q[2] / n, q[3] / n)


def quat_to_mat3(q):
    """Rotation matrix as three rows."""
    x, y, z, w = quat_normalize(q)
    xx, yy, zz = x * x, y * y, z * z
    xy, xz, yz = x * y, x * z, y * z
    wx, wy, wz = w * x, w * y, w * z
    return [
        [1.0 - 2.0 * (yy + zz), 2.0 * (xy - wz), 2.0 * (xz + wy)],
        [2.0 * (xy + wz), 1.0 - 2.0 * (xx + zz), 2.0 * (yz - wx)],
        [2.0 * (xz - wy), 2.0 * (yz + wx), 1.0 - 2.0 * (xx + yy)],
    ]


def mat3_from_columns(u, v, w):
    return [[u[0], v[0], w[0]],
            [u[1], v[1], w[1]],
            [u[2], v[2], w[2]]]


def mat3_transpose(m):
    return [[m[0][0], m[1][0], m[2][0]],
            [m[0][1], m[1][1], m[2][1]],
            [m[0][2], m[1][2], m[2][2]]]


def mat3_mul(a, b):
    return [[sum(a[i][k] * b[k][j] for k in range(3)) for j in range(3)]
            for i in range(3)]


def quat_from_mat3(m):
    """Quaternion of a rotation matrix (Shepperd's stable branch choice)."""
    t = m[0][0] + m[1][1] + m[2][2]
    if t > 0.0:
        s = math.sqrt(t + 1.0) * 2.0
        w = 0.25 * s
        x = (m[2][1] - m[1][2]) / s
        y = (m[0][2] - m[2][0]) / s
        z = (m[1][0] - m[0][1]) / s
    elif m[0][0] > m[1][1] and m[0][0] > m[2][2]:
        s = math.sqrt(1.0 + m[0][0] - m[1][1] - m[2][2]) * 2.0
        w = (m[2][1] - m[1][2]) / s
        x = 0.25 * s
        y = (m[0][1] + m[1][0]) / s
        z = (m[0][2] + m[2][0]) / s
    elif m[1][1] > m[2][2]:
        s = math.sqrt(1.0 + m[1][1] - m[0][0] - m[2][2]) * 2.0
        w = (m[0][2] - m[2][0]) / s
        x = (m[0][1] + m[1][0]) / s
        y = 0.25 * s
        z = (m[1][2] + m[2][1]) / s
    else:
        s = math.sqrt(1.0 + m[2][2] - m[0][0] - m[1][1]) * 2.0
        w = (m[1][0] - m[0][1]) / s
        x = (m[0][2] + m[2][0]) / s
        y = (m[1][2] + m[2][1]) / s
        z = 0.25 * s
    return quat_normalize((x, y, z, w))


def quat_to_axis_angle(q):
    """``(axis, angle)`` with ``angle`` in ``[0, pi]``."""
    x, y, z, w = quat_normalize(q)
    if w < 0.0:
        x, y, z, w = -x, -y, -z, -w
    s = math.sqrt(max(0.0, 1.0 - w * w))
    angle = 2.0 * math.acos(clamp(w, -1.0, 1.0))
    if s < 1e-9:
        return ((0.0, 0.0, 1.0), 0.0)
    return ((x / s, y / s, z / s), angle)


def quat_slerp(a, b, t):
    """Shortest-arc spherical interpolation."""
    a = quat_normalize(a)
    b = quat_normalize(b)
    d = a[0] * b[0] + a[1] * b[1] + a[2] * b[2] + a[3] * b[3]
    if d < 0.0:
        b = (-b[0], -b[1], -b[2], -b[3])
        d = -d
    if d > 0.9995:
        out = tuple(a[i] + (b[i] - a[i]) * t for i in range(4))
        return quat_normalize(out)
    theta = math.acos(clamp(d, -1.0, 1.0))
    st = math.sin(theta)
    wa = math.sin((1.0 - t) * theta) / st
    wb = math.sin(t * theta) / st
    return quat_normalize(tuple(a[i] * wa + b[i] * wb for i in range(4)))


# --------------------------------------------------------------------------
# similarity transform
# --------------------------------------------------------------------------

class Transform(object):
    """A similarity transform ``p -> scale * (rotation * p) + translation``.

    Uniform scale only.  Non-uniform scaling is deliberately not part of the
    two-handed gesture vocabulary: with two grab points the only well posed
    scale is the ratio of the hand separation, which is uniform by
    construction, and a non-uniform scale would make the composition of two
    gestures depend on their order in a way that feels wrong in the headset.
    Object-level non-uniform size lives in the primitive parameters instead
    (:mod:`xrsketch.primitives`).
    """

    __slots__ = ("translation", "rotation", "scale")

    def __init__(self, translation=(0.0, 0.0, 0.0), rotation=IDENTITY_QUAT,
                 scale=1.0):
        self.translation = vec3(translation)
        self.rotation = quat_normalize(rotation)
        self.scale = float(scale)

    # -- construction ----------------------------------------------------
    @classmethod
    def identity(cls):
        return cls()

    @classmethod
    def from_dict(cls, d):
        if d is None:
            return cls()
        return cls(d.get("translation", (0.0, 0.0, 0.0)),
                   d.get("rotation", IDENTITY_QUAT),
                   d.get("scale", 1.0))

    def to_dict(self):
        return {"translation": list(self.translation),
                "rotation": list(self.rotation),
                "scale": self.scale}

    def copy(self):
        return Transform(self.translation, self.rotation, self.scale)

    # -- use -------------------------------------------------------------
    def apply(self, p):
        r = quat_rotate(self.rotation, vec3(p))
        return (r[0] * self.scale + self.translation[0],
                r[1] * self.scale + self.translation[1],
                r[2] * self.scale + self.translation[2])

    def apply_vector(self, v):
        """Apply rotation and scale but not translation."""
        r = quat_rotate(self.rotation, vec3(v))
        return mul(r, self.scale)

    def then(self, outer):
        """``outer ∘ self``: this transform first, then ``outer``."""
        return compose(outer, self)

    def inverse(self):
        s = 1.0 / self.scale if abs(self.scale) > EPS else 0.0
        qi = quat_conjugate(self.rotation)
        t = quat_rotate(qi, mul(self.translation, -s))
        return Transform(t, qi, s)

    def matrix(self):
        """Row-major 4x4."""
        m = quat_to_mat3(self.rotation)
        s = self.scale
        t = self.translation
        return [[m[0][0] * s, m[0][1] * s, m[0][2] * s, t[0]],
                [m[1][0] * s, m[1][1] * s, m[1][2] * s, t[1]],
                [m[2][0] * s, m[2][1] * s, m[2][2] * s, t[2]],
                [0.0, 0.0, 0.0, 1.0]]

    def almost_equal(self, other, tol=1e-9):
        if abs(self.scale - other.scale) > tol:
            return False
        if dist(self.translation, other.translation) > tol:
            return False
        d = abs(sum(self.rotation[i] * other.rotation[i] for i in range(4)))
        return abs(d - 1.0) <= tol

    def __repr__(self):
        return "Transform(t=%s, s=%.6g)" % (
            tuple(round(v, 6) for v in self.translation), self.scale)


def compose(outer, inner):
    """The transform equivalent to applying ``inner`` and then ``outer``."""
    scale = outer.scale * inner.scale
    rotation = quat_mul(outer.rotation, inner.rotation)
    translation = add(outer.apply_vector(inner.translation),
                      outer.translation)
    return Transform(translation, rotation, scale)


Transform.compose = staticmethod(compose)
